<blockquote>
  <p>Auch wenn es sich manchmal so anhört, als sei mit dem Wechsel zu tabellenlosem Design die Welt komplizierter geworden, stimmt dies so nicht. Der Verzicht auf Layouttabellen zwingt zu einer Betrachtung des Seiteninhaltes, nicht der Optik und macht so die Sicht klarer auf den eigentlichen Charakter der Seite. Zudem öffnen sich auch neue Möglichkeiten mit CSS, die man in dieser Form mit einem puren Tabellendesign nicht hat. Mittels CSS können beispielsweise Objekte gestapelt werden. So könnte man zwei Bilder sich überlappen lassen oder Text über ein Bild legen.</p>
  <cite>Jens Grochtdreis, Webkrauts</cite>
</blockquote>
